- [Project overview](wp-platform-project.md) — WP装备能源AI经营管理平台架构、技术栈、模块状态
- [KPI rules](wp-platform-kpi-platform-rules.md) — 所有绩效考核KPI的详细计算规则
- [便利贴待办](weekly-plan-app.md) — Daily_plan PySide6桌面便利贴待办应用
- [写作风格](user-writing-style.md) — 用户正式公文写作风格记录（持续积累）
- [故障率分析引擎](failure-analysis-engine.md) — 作业率故障率分析算法、CLI/API使用、配置规则
